### ISSUE TITLE
racer fails when rust is installed on a read-only filesystem

### ISSUE THREAD

**Issue by wizeman** [phildawes/racer#124] opened 2015-01-27 17:08 UTC
When using `racer` on `NixOS`, which mounts system directories read-only, `racer` fails to jump to a definition with the following error:

```
/nix/store/vkwcg4igwwaw7qiy3pvd0n2bidj61wqc-rust-a833337/src/libstd/io/net/pipe.rs [RO]                                                                                                          58,32           4%
"/nix/store/vkwcg4igwwaw7qiy3pvd0n2bidj61wqc-rust-a833337/src/libstd/io/net/pipe.rs.racertmp"
Error detected while processing function racer#GoToDefinition:
line    1:
"/nix/store/vkwcg4igwwaw7qiy3pvd0n2bidj61wqc-rust-a833337/src/libstd/io/net/pipe.rs.racertmp" E212: Can't open file for writing
```

The error happens because (as I mentioned above) `/nix/store`, which is the system directory (and also where rust gets installed), is read-only.

**Comment by phildawes** [comment] 2015-01-28 07:10
Hi Wizeman,
Thanks for the report. I am working on racer not needing to save temporary files. I'm a bit limited on time this week but hopefully will have something soon. Sorry!

**Comment by phildawes** [comment] 2015-02-02 18:47
Hi Wizeman,

It's just occurred to me that in this specific case the problem isn't with the racer core but rather with the vim plugin: it doesn't need to save a temporary file if the buffer is unchanged, it could just pass the filename directly to racer. Do you have any vim script experience to try and fix this?

Cheers,

Phil

**Comment by wizeman** [comment] 2015-02-02 18:56
@phildawes Sorry, but I don't... my vim knowledge is rather basic.

**Comment by ebfe** [comment] 2015-02-02 19:27
[`:help 'modified'`](http://vimdoc.sourceforge.net/htmldoc/options.html#%27modified%27)

**Comment by wizeman** [comment] 2015-02-02 19:52
According to @ebfe's pointer, could the problem be that `fileencoding` is being set?

I'm using this as my `/etc/vimrc`, which indeed seems to set `fileencoding`: http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/app-editors/vim-core/files/vimrc-r4?revision=1.3

I'm also using `Vundle` in my `~/.vimrc`.

**Comment by wizeman** [comment] 2015-02-02 19:57
By the way, the error only happens when I jump to a system-library definition **twice in a row**, e.g.:
* When I jump from my code to e.g. the definition of `UnixStream`, it will work fine
* If I then jump from the `io/net/pipe.rs` code (where `UnixStream` is defined) to e.g. the definition of `IoResult`, I get the mentioned error

**Comment by ebfe** [comment] 2015-02-02 20:14
> By the way, the error only happens when I jump to a system-library definition **twice in a row**, e.g.:
> * When I jump from my code to e.g. the definition of `UnixStream`, it will work fine
> * If I then jump from the `io/net/pipe.rs` code (where `UnixStream` is defined) to e.g. the definition of `IoResult`, I get the mentioned error

Thats because your code presumably resides in a writable directory and
io/net/pipe.rs is not. The vim plugin tries to write to `%:p.racertmp`
where '%:p' is the current file.

Sorry for beeing too brief. The reference to `'modified'` was mostly
because it is an easy way to check if the current buffer has been
modified (in case anyone wants to implement the workaround suggested by
@phildawes).

**Comment by Shougo** [comment] 2015-08-25 11:00
It is fixed by https://github.com/phildawes/racer/pull/344.
It should be closed.

**Closed** 2015-08-28 06:52 UTC
Labels: bug-vim
