### ISSUE TITLE
Racer uses a ridiculous amount of resources in some situations

### ISSUE THREAD

**Issue by nstoddard** [phildawes/racer#273] opened 2015-06-14 22:38 UTC
I use Sublime Text with Racer, on Windows 7, and I had started typing the following line when Racer started using a ton of resources:

```
panic!("trying
```

Racer started using the hard drive a lot (and possibly using other resources, I couldn't tell), and it froze my computer (I couldn't do anything but move the mouse cursor). I had to hold the power button to reboot. This happened while I was typing the word 'trying'. After I rebooted, I tried this again, and the same thing happened, but I was able to kill racer before my computer froze completely.

I don't know why this particular line triggered the problem; racer has worked fine on everything else so far.

**Comment by phildawes** [comment] 2015-06-15 05:54
Hi @nstoddard,
Thanks for the report. I suspect racer got itself into some sort of loop. I can't reproduce this with just the line 'panic!("trying', what else was in the file?

Thanks,

Phil

**Comment by nstoddard** [comment] 2015-06-15 06:53
I was working on a multiset data structure. I didn't save an exact copy of the code, but it looked something like this (I took the finished file and tried to remove stuff that I wrote after I encountered the problem):

```
use std::collections::hash_map::*;
use std::hash::Hash;
use std::ops::*;

pub struct Multiset<K: Eq + Hash> {
    elems: HashMap<K, u32>,
    // This is a stupid hack to avoid 'does not live long enough' in get()
    zero: u32,
}

impl<K: Eq + Hash> Multiset<K> {
    pub fn new() -> Self {
        Multiset{elems: HashMap::new(), zero: 0}
    }

    pub fn insert(&mut self, val: K) -> u32 {
        match self.elems.entry(val) {
            Entry::Vacant(entry) => {
                entry.insert(1);
                1
            }
            Entry::Occupied(mut entry) => {
                let view = entry.get_mut();
                *view += 1;
                *view
            }
        }
    }

    pub fn get(&self, val: K) -> &u32 {
        self.elems.get(&val).unwrap_or(&self.zero)
    }

    pub fn remove(&mut self, val: K) -> u32 {
        match self.elems.entry(val) {
            Entry::Vacant(_) => panic!("Unable to remove elem from Multiset (vacant)"),
            Entry::Occupied(mut entry) => {
                if *entry.get() == 0 {
                    panic!(   <--- I was writing this line
                }
            }
        }
    }
}
```
I was writing the line containing the `panic` near the bottom. This code was in 'main.rs' (I also had an empty main() function for testing) and I wasn't using Cargo.

I'm reluctant to try to repro the problem right now, since I've got a bunch of stuff open that I don't want to lose if it freezes again. So I'm not sure if this code actually triggers the problem.

**Comment by phildawes** [comment] 2015-06-15 19:55
Hi @nstodard,
I'm not 100% sure if this reproduces your freezing problem, but it certainly reproduces an issue:
On linux when compiling in debug I get an 'arithmetic operation overflowed'[1] in racer::scopes line 253. It seems that 'pos' is less than 'start' in the following:

```rust
        for _ in 0..((pos - start)/128) { result.push_str(buffer); }
```
I suspect in release mode this isn't getting caught and the result is a massive 'result' vec. I haven't got time to debug this right now, but will take a look asap.

Thanks v much!

Phil

**Comment by tafia** [comment] 2015-06-16 16:06
I couldn't reproduce on my side but I found another issue (#275)
Perhaps it is linked somehow ...

**Comment by phildawes** [comment] 2015-07-20 18:26
I think this might be fixed now (at least I can't reproduce the problem where I used to be able to).
Thanks again @nstoddard

**Closed by phildawes** 2015-07-20 18:26 UTC
