### ISSUE TITLE
Use an argument parsing library

### ISSUE THREAD

**Issue by marvelm** [phildawes/racer#326] opened 2015-08-07 00:18 UTC
Would you be opposed to me adding another dependency (https://github.com/tailhook/rust-argparse) and cleaning up the argument handling in main.rs ?

**Comment by phildawes** [comment] 2015-08-07 06:27
Sounds good. Is it the code you want to clean up, or were you thinking of
changing the arguments? If the latter we will need to make sure plugins
remain compatible

**Comment by marvelm** [comment] 2015-08-08 16:41
Sorry for not responding sooner.
I tried to use rust-argparse, but it didn't seem to improve the code quality. I think we should use Docopt (https://github.com/docopt/docopt.rs) instead. It takes a usage string, a struct, and decodes args into the struct. I have an example of this at https://github.com/marvelm/racer/blob/effe804/src/bin/main.rs#L188
I don't think the commands/arguments will change.

**Comment by cburgdorf** [comment] 2015-08-13 23:01
I suggest using github.com/kbknapp/clap-rs. It has the best API I've seen so far and is very well maintained by @kbknapp

**Comment by kbknapp** [comment] 2015-08-14 01:38
Thanks for the kind words! I've put together a gist of what `main.rs` would look like using `clap` at https://gist.github.com/kbknapp/f71a574d89abbe966d8d

This is truly a one-for-one port, all functionality should be exactly the same, plus all the extras added by `clap` for free, so to speak (Noted below).

A few things to note about this:

* There are some oddities when using the first argument after `complete` as *either* a line number or a fully-qualified-name. This one-for-one port says, "The first argument is required (either line number or FQN), and only if a second argument is found (`charnum`) then a third argument also becomes required (`fname`)" There is probably a cleaner way to do this, but not without changing the interface in some manner (such as adding flags, or changing subcommand names, etc.)
* You get suggestions for free; say a user types `racer compete std::io::B` (note the missing `L` in comp**l**ete) they would see an error saying, "the subcommand 'compete' isn't valid, did you mean 'complete'?"
* You get "smart usage strings" or what I sometimes call "context aware" usage strings. For example, if you were to run `racer complete 250 20` you'll get an error saying `fname` wasn't provided but is required, in the suggested usage string, the user will see `racer complete <fqn or linenum> [charnum] [fname]` even though `charnum` and `fname` are technically optional, they aren't in this *context* so they are included.
* I work pretty hard to keep `clap` efficient, so you get all the above with *very, very* few allocations.

I'd recommend trying it out, playing with some errors, testing speed / efficiency, etc. If you'd like, I can put in a PR.

No pressure to use `clap`, by they way! It's totally your project, and you're free to use whatever you choose :) In fact, I'll be the first to say, `Docopt` does some thing better than `clap`, and vice versa. Sometimes when all tests that matter to you come out equal, it comes down to personal taste!

**Comment by tafia** [comment] 2015-08-14 02:20
:+1:

**Comment by marvelm** [comment] 2015-08-14 18:08
I took a look at `clap` and .

The one obvious disadvantage of `Docopt` is that code using an invalid usage can be compiled with no error. The author has a compiler plugin and macro to check the usage string and generate a config struct at compile time, but it only works on a nightly compiler. This can be mitigated by writing a test to create an instance of `Docopt` with the usage string and catching parsing errors.

**Comment by kbknapp** [comment] 2015-08-15 04:38
@marvelm thanks! Also, to be fair, it's somewhat possible to do the same with `clap`. Although it's trivial to test against. With `clap` if you have a test that builds the valid command line arguments in the same way, and you call `App::get_matches()` with no `panic!` you're good. But this still won't fix a user typo, only verifies a working `App` struct with valid arguments.

While testing I became curious about speed, as I'm assuming racer needs to complete the matches as fast as possible. I've put together some (*very*) naive tests comparing vanilla `racer` to those using `clap` and `docopt`. The gist can be see here:

**Comment by birkenfeld** [comment] 2015-08-29 12:27
I updated the branch in [my fork](https://github.com/birkenfeld/racer/tree/clap). The timings and allocations are now
```
$ python -m timeit -n 1 -r 200 -s 'import os' 'os.system("target/release/master complete std::io::")'
1 loops, best of 200: 9.36 msec per loop
$ valgrind target/release/master complete std::io:: > /dev/null
==15544==   total heap usage: 7,205 allocs, 7,205 frees, 1,574,929 bytes allocated

$ python -m timeit -n 1 -r 200 -s 'import os' 'os.system("target/release/clap complete std::io::")'  
1 loops, best of 200: 9.42 msec per loop
$ valgrind target/release/clap complete std::io:: > /dev/null  
==15565==   total heap usage: 7,364 allocs, 7,364 frees, 1,808,937 bytes allocated
```

**Comment by kbknapp** [comment] 2015-08-29 14:48
@birkenfeld That prompted me to update to the latest master here (since there have been massive performance improvments) and update `clap` as well. The gist posted above has been updated, but here's the relevant data:

```
Vanilla phildawes/master#ebc55c07bb
    Number of Allocs: 1,192
    Bytes Allocated: 486,449
    Python: best of 100: 5.17 msec per loop
    Average time: r 0.01, u 0.00, s 0.007

clap v1.2.5 kbknapp/clap-update#744313c512
    Number of Allocs: 1,345 (+153 over latest vanilla)
    Bytes Allocated: 634,521 (+148,072 over latest vanilla)
    Python: best of 100: 5.07 msec per loop
    Average time: r 0.01, u 0.00, s 0.07
```

Because `clap` came out faster using python, that prompted me to up the iterations. When using `-r 1000` (1,000 iterations instead of 100) the results are:

```
vanilla: best of 1000: 4.98 msec per loop
clap:   best of 1000: 5.05 msec per loop
```

Which makes more sense, but I'm glad to see see `clap` keeping up :smile:

**Comment by birkenfeld** [comment] 2015-08-29 14:59
Yeah, 9.36 vs 9.42 is basically noise. As for docopt, I think it proved to have a nontrivial cost that should be avoided for this use case.

@kbknapp a few observations:

* is it possible to print the entire help text when no subcommand is given? It only tells me 
```
error: 'racer' requires a subcommand but none was provided

USAGE:
        racer <SUBCOMMAND>

For more information try --help
```
which is not so helpful (sure, `--help` is advertised so no big problem, but it it seems like this should be in the message already).

* `racer complete --help` is not the same as `racer --help complete` which may be confusing to people.

* this help doesn't really tell me much about the two possible syntaxes:
```
USAGE:
        racer complete [FLAGS] [ARGS] <fqn or linenum>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

ARGS:
    fqn or linenum     complete with a fully-qualified-name (e.g. std::io::) or line number
    charnum            The char number
    fname              The function name to match
    substitute_file    An optional substitute file
```
Especially `[ARGS] <fqn or linenum>` is strange, since `<fqn or linenum>` is already in ARGS.

**Comment by kbknapp** [comment] 2015-08-29 15:33
@birkenfeld 

> is it possible to print the entire help text when no subcommand is given?

Yes. Just change [these lines](https://github.com/kbknapp/racer/blob/744313c512514d82bbf736c57d0aa8fbffe99fab/src/bin/main.rs#L183-L184) to:

```rust
.global_version(true)
.subcommand_required_else_help(true)
```
OR use the new syntax which is a little prettier (but does the same thing)

```rust
.settings( &[AppSettings::GlobalVersion,
             AppSettings::SubcommandRequiredElseHelp])
```

> `racer complete --help` is not the same as `racer --help complete` which may be confusing to people.

I agree. But I think after making the change described above to give the full help on lack of a command it's almost a non-issue. Since at the bottom it says `For more information about a specific command try 'racer <command> --help'`

> this help doesn't really tell me much about the two possible syntaxes:

This part I totally agree with, which is what I was eluding to earlier when I said there are probably better ways to structure the CLI in general (as in the interface, not code itself). There are some new-ish features of `clap` which can *help* but it's not perfect. It breaks down to 3 options without having a breaking CLI change:

* Lie about the arg name which gets displayed to the user. You tell clap the arg name is `[<fqn> | <lineno>]` which gets displayed to the user in that format in the usage string. This is the easiest method, and least breaking. 
* Use `FQN` and `LINENO` as separate args, but part of an `ArgGroup` so they're mutually exclusive with each other. You then make the group required, but not the args. This means one of the args must be present, but not both. The hard part is, because they're just free floating positional args, you have to manually determine which one the user used, because to clap they look the same.
* Use a custom usage string (`clap` allows you define whatever usage string you want instead of auto generating it), which entirely solves the problem. The only downside is usage strings on errors aren't dynamic at that point. Meaning, typically when you make an error, `clap` will take whatever args you were *trying* to use, and stick them in the usage string displayed at error regardless if they were actually required or not (unless there is some conflict, which it determines as well). This is nice if you have a ton of args you're passing in, and you make an error with one of them, you see how the command should have actually been called giving all the options you were trying to use, and not just a static usage string.

> [ARGS] <fqn or linenum> is strange, since <fqn or linenum> is already in ARGS.

I see what you mean. What it's trying to convey though is that `[ARGS]` are optional positional free floating args. But `<fqn or lineno>` is required. Hence the `[]` and `<>` but you're right, that could be confusing. Although I think the user would figure it out quite quickly.

Sorry for the long reply, I can be long winded! :smile: And those are all great points you brought up, I can update the branch I was using for testing to demo some of these options/changes if you like! :smile:

**Comment by kbknapp** [comment] 2015-08-30 04:03
@birkenfeld I've made some of those changes so you can see what it looks like. See [clap-update#6b4ff42f](https://github.com/kbknapp/racer/commit/6b4ff42f264fd81c13848fa48a53d1369e485b00) to test. This is using the second method described above.

**Comment by kbknapp** [comment] 2015-10-07 00:09
@birkenfeld based off some of the changes in `clap` I updated the gist and branch in my fork (based off the latest master here). Results are somewhat strange as the `clap` version comes out faster than vanilla and shows way fewer allocations...I'm not really sure why that would be.

For the interested the [branch update](https://github.com/kbknapp/racer/tree/65dd81611c762d2d27a44868275c926f2b5b23c7) and [gist](https://gist.github.com/kbknapp/fb28a49d7a0fe8b8e400)

**Comment by birkenfeld** [comment] 2015-10-07 05:54
Hm, I could not reproduce this exactly; for me both master and clap-update show the same number of allocs as your clap-update measurement (13 allocs, 67k bytes). Timing goes from 2.56 to 2.63 ms with clap, which is fine.

At this point, I would recommend opening a pull request!

**Comment by kbknapp** [comment] 2015-10-07 16:06
May have been a typo or mis-test on my part...because I'm getting the same now :confounded: Oh well! Gist is updated :smile:

**Comment by kbknapp** [comment] 2015-11-20 17:53
v1.5.3 has some pretty major improvements both in terms of performance and features, so I'll try to update the gist shortly...

**Comment by mackwic** [comment] 2016-02-29 11:03
I think you can close this issue, now :+1:

**Closed** 2016-09-08 18:23 UTC
